#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 19 15:32:19 EST 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim multi_core_test_behav -key {Behavioral:sim_1:Functional:multi_core_test} -tclbatch multi_core_test.tcl -log simulate.log"
xsim multi_core_test_behav -key {Behavioral:sim_1:Functional:multi_core_test} -tclbatch multi_core_test.tcl -log simulate.log

