## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk100m]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk100m]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk100m]
# Switches
set_property PACKAGE_PIN V17 [get_ports {switches[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]
set_property PACKAGE_PIN V16 [get_ports {switches[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]
set_property PACKAGE_PIN W16 [get_ports {switches[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[2]}]
set_property PACKAGE_PIN W17 [get_ports {switches[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[3]}]
set_property PACKAGE_PIN W15 [get_ports {switches[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[4]}]
set_property PACKAGE_PIN V15 [get_ports {switches[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[5]}]
set_property PACKAGE_PIN W14 [get_ports {switches[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[6]}]
set_property PACKAGE_PIN W13 [get_ports {switches[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[7]}]
#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports {cathode_pattern[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[6]}]
set_property PACKAGE_PIN W6 [get_ports {cathode_pattern[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[5]}]
set_property PACKAGE_PIN U8 [get_ports {cathode_pattern[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[4]}]
set_property PACKAGE_PIN V8 [get_ports {cathode_pattern[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[3]}]
set_property PACKAGE_PIN U5 [get_ports {cathode_pattern[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[2]}]
set_property PACKAGE_PIN V5 [get_ports {cathode_pattern[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[1]}]
set_property PACKAGE_PIN U7 [get_ports {cathode_pattern[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cathode_pattern[0]}]
set_property PACKAGE_PIN U2 [get_ports {anode_activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode_activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode_activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode_activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[3]}]
##Buttons
set_property PACKAGE_PIN U18 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN T18 [get_ports clk_reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports clk_reset]
